version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.40.0
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "55678:55678" 
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
