receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:55678
        cors_allowed_origins: http://localhost:3000

exporters:
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
  jaeger:
    endpoint: "jaeger-all-in-one:14250"
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin, jaeger]
      processors: [batch]